spring:
  application:
    name: air_jet

  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB

  jackson:
    default-property-inclusion: non_null

  profiles:
    active: default,dev,aws



server:
  port: 7757